export const SET_UNIDADMEDIDA_DATA = 'src/Empresa/SET_UNIDADMEDIDA_DATA';
export const ID_SELECTED_UNIDADMEDIDA = 'src/Empresa/ID_SELECTED_UNIDADMEDIDA';
export const FETCH_UNIDADMEDIDA = 'src/Empresa/FETCH_UNIDADMEDIDA';
export const EDIT_UNIDADMEDIDA = 'src/Empresa/EDIT_UNIDADMEDIDA';
export const EDIT_TIPO = 'src/Empresa/EDIT_TIPO';
export const CREACION_REGISTRO_UNIDADMEDIDA = 'src/Empresa/CREACION_REGISTRO_UNIDADMEDIDA';
