export const SET_LISTADOPRODUCTOS_DATA = 'src/LISTADOPRODUCTOS/SET_LISTADOPRODUCTOS_DATA';
export const ID_SELECTED_LISTADOPRODUCTOS = 'src/LISTADOPRODUCTOS/ID_SELECTED_LISTADOPRODUCTOS';
export const FETCH_LISTADOPRODUCTOS = 'src/LISTADOPRODUCTOS/FETCH_LISTADOPRODUCTOS';
export const EDIT_LISTADOPRODUCTOS = 'src/LISTADOPRODUCTOS/EDIT_LISTADOPRODUCTOS';
export const EDIT_TIPO = 'src/LISTADOPRODUCTOS/EDIT_TIPO';
export const CREACION_REGISTRO_LISTADOPRODUCTOS = 'src/LISTADOPRODUCTOS/CREACION_REGISTRO_LISTADOPRODUCTOS';
export const AUTORIZACION_FORM_FAIL = 'src/LISTADOPRODUCTOS/AUTORIZACION_FORM_FAIL';
