export const SET_DATA_FACTURA = 'SET_DATA_FACTURA';
export const FETCH_DATA_FACTURA = 'FETCH_DATA_FACTURA';
export const SET_DATA_PRODUCCION = 'SET_DATA_PRODUCCION';
export const FETCH_DATA_PRODUCCION = 'FETCH_DATA_PRODUCCION';
export const FETCH_DATA_DETALLE_PRODUCCION = 'FETCH_DATA_DETALLE_PRODUCCION';
export const SET_DATA_DETALLE_PRODUCCION = 'SET_DATA_DETALLE_PRODUCCION';
export const UPDATE_DETALLE_CANTIDAD = 'UPDATE_DETALLE_CANTIDAD';
