export const CLICK_FACTURA = 'CLICK_FACTURA';
export const CHECK_CABECERA_FACTURA = 'CHECK_CABECERA_FACTURA';
export const REVISAR_ESTADO_CLICK = 'REVISAR_ESTADO_CLICK';
export const BANDERA_CABECERA_REMOVE = 'BANDERA_CABECERA_REMOVE';
export const CHECK_DETALLE_FACTURA = 'CHECK_DETALLE_FACTURA';
