export const CLICK_FACTURA = 'CLICK_FACTURA';
export const CHECK_CABECERA_FACTURA = 'CHECK_CABECERA_FACTURA';
export const REVISAR_ESTADO_CLICK = 'REVISAR_ESTADO_CLICK';
export const BANDERA_CABECERA_REMOVE = 'BANDERA_CABECERA_REMOVE';
export const CHECK_DETALLE_FACTURA = 'CHECK_DETALLE_FACTURA';
export const ACTUALIZACION_LISTA_FACTURA_DETALLE = 'ACTUALIZACION_LISTA_FACTURA_DETALLE';
export const LISTA_FACTURA_DETALLE_CREADA = 'LISTA_FACTURA_DETALLE_CREADA';
