export const SET_TIPOPRODUCTO_DATA = 'src/Empresa/SET_TIPOPRODUCTO_DATA';
export const ID_SELECTED_TIPOPRODUCTO = 'src/Empresa/ID_SELECTED_TIPOPRODUCTO';
export const FETCH_TIPOPRODUCTO = 'src/Empresa/FETCH_TIPOPRODUCTO';
export const EDIT_TIPOPRODUCTO = 'src/Empresa/EDIT_TIPOPRODUCTO';
export const EDIT_TIPO = 'src/Empresa/EDIT_TIPO';
export const CREACION_REGISTRO_TIPOPRODUCTO = 'src/Empresa/CREACION_REGISTRO_TIPOPRODUCTO';
