export const SET_USUARIOS_DATA = 'src/USUARIOS/SET_USUARIOS_DATA';
export const ID_SELECTED_USUARIOS = 'src/USUARIOS/ID_SELECTED_USUARIOS';
export const LOGIN_WATCHER = 'src/USUARIOS/LOGIN_WATCHER';
export const FETCH_USUARIOS = 'src/USUARIOS/FETCH_USUARIOS';
export const EDIT_USUARIOS = 'src/USUARIOS/EDIT_USUARIOS';
export const EDIT_TIPO = 'src/USUARIOS/EDIT_TIPO';
export const CREACION_REGISTRO_USUARIOS = 'src/USUARIOS/CREACION_REGISTRO';
export const AUTORIZACION_FORM_FAIL = 'src/USUARIOS/AUTORIZACION_FORM_FAIL';
